channels:
- uibcdf
- conda-forge
dependencies:
- python>=3.11,<3.15
- pip
- setuptools >=61.0
- versioningit ~=2.0
- argdigest
- depdigest>=0.12.0
- molsysmt
- numba
- numpy
- pyunitwizard
- scipy
- smonitor
