schema_version: 1
workflows:
  - match:
      path: .github/workflows/CI.yaml
    profile: ci
  - match:
      path: .github/workflows/build_and_upload_conda_packages.yaml
    profile: conda
    settings:
      expected_platforms:
        - linux-64
        - osx-64
        - osx-arm64
        - win-64
  - match:
      path: .github/workflows/ruff.yaml
    profile: ci
  - match:
      path: .github/workflows/sphinx_docs_to_gh_pages.yaml
    profile: docs
