setup:
  channels: &setup_channels
    - uibcdf
    - conda-forge
  dependencies: &setup_dependencies
    - python
    - pip
    - setuptools >=61.0
    - versioningit ~=2.0

production:
  channels: &production_channels
    - *setup_channels
  dependencies: &production_dependencies
    - *setup_dependencies
    - argdigest
    - depdigest >=0.12.0
    - molsysmt
    - numba
    - numpy
    - smonitor
    - pyunitwizard
    - scipy
    - nglview

test:
  channels: &test_channels
    - *production_channels
  dependencies: &test_dependencies
    - *production_dependencies
    - pytest
    - pytest-cov
    - pytest-xdist
    - codecov

docs:
  channels: &docs_channels
    - *production_channels
  dependencies: &docs_dependencies
    - *production_dependencies
    - jupyterlab
    - plantuml
    - graphviz
    - sphinx
    - pydata-sphinx-theme
    - sphinxcontrib-bibtex
    - sphinx-remove-toctrees
    - sphinx-copybutton
    - sphinx-design
    - sphinx-favicon
    - sphinx-tabs
    - sphinxcontrib-plantuml
    - myst-nb
    - fpocket

development:
  channels:
    - *production_channels
  dependencies:
    - *production_dependencies
    - *test_dependencies
    - *docs_dependencies
    - mamba

conda-build:
  channels:
    - *production_channels
  dependencies:
    - anaconda-client
    - conda-build

