name: Conda publication governance
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  publication:
    uses: uibcdf/molsyssuite/.github/workflows/check-conda-publication.yaml@42e4de425871c125ef058842075c39e50fc6ac64
