name: MolSysSuite policy

on:
  push:
    branches: [main]
    tags: ["*"]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  policy:
    uses: uibcdf/molsyssuite/.github/workflows/check-python-repository.yaml@policy-v1.4.0
